### ISSUE TITLE
WindDirection int or float?

### ISSUE THREAD

**Issue by Foxtrot1388** [HectorMalot/omgo#3]
Hello, could you help me? I have an error:
encoding/json.UnmarshalTypeError {Value: "number 14.0", Type: reflect.Type(*reflect.rtype) *{size: 8, ptrdata: 0, hash: 4149441018, tflag: tflagUncommon|tflagExtraStar|tflagNamed|tflagRegularMemory (15), align: 8, fieldAlign: 8, kind: 2, equal: runtime.memequal64, gcdata: *0, str: 2035, ptrToThis: 301824}, Offset: 255, Struct: "CurrentWeather", Field: "current_weather.WindDirection"}

Apparently WindDirection int in the code, but it comes with a dot (14.0). Or is there a mistake somewhere else?

**Comment by Foxtrot1388** [comment]
Hmm, "go get latest" is using version v0.1.2 on Releases where there is this issue

**Comment by HectorMalot** [comment]
in the docs its shown as degrees, the examples are ints, but it is not formally specified. 

I would need to change all ints to floats if this persists, and we can't assume the API consistently returns ints. Will ask open-meteo what the expected type should be.

**Comment by Foxtrot1388** [comment]
The problem is fixed in the version above 0.1.2 in commit, it seems that the problem is that the new version of the tag is missing

**Comment by HectorMalot** [comment]
I’ll likely tag it 0.1.3, will await the question at open meteo first:  https://github.com/open-meteo/open-meteo/issues/410

**Comment by HectorMalot** [comment]
Fixed in ddd9984
